name: Jest
on: pull_request

defaults:
  run:
    working-directory: backend

jobs:
  jest:
    runs-on: ubuntu-latest
    container: node:18.12.0

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: prisma2020
          POSTGRES_DB: prisma
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test:integration
        env:
          DATABASE_URL: 'postgresql://root:prisma2020@postgres:5432/prisma?schema=public'
          STAGE: 'test'
